### ISSUE TITLE
look for swool resource

### ISSUE THREAD

**Issue by guangzhouhengda1991** [GiggleAll/php#29]
_

1. **do you have?**

_

**Comment by threadshare** [comment]
sorry  i did not used swool




            
            
                
                    
                            
                                
                            
                            
                                master
                            
                    
                        
                            
                                    邮箱：master@io404.net
                            
                        
                
            
        


On 02/29/2020 18:42, guangzhouhengda1991 wrote: _

do you have?

_

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/threadshare/php/issues/29?email_source=notifications\u0026email_token=ADCF2Q4QZQ5EOI64ABBLDT3RFDS7NA5CNFSM4K6UCVY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IRLNSGA",
"url": "https://github.com/threadshare/php/issues/29?email_source=notifications\u0026email_token=ADCF2Q4QZQ5EOI64ABBLDT3RFDS7NA5CNFSM4K6UCVY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IRLNSGA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by threadshare** [comment]
Maybe you can  pr this content if you have found it about swool.
